### ISSUE TITLE
SecurityRAT-dockercompose fails to start due to tomcat error

### ISSUE THREAD

**Issue by AresSec** [SecurityRAT/SecurityRAT#113]
The current build of the dockercompose file crashes during startup with the following exception:

securityrat      | [ERROR] org.springframework.boot.context.embedded.tomcat.TomcatStarter - Error starting Tomcat context: org.springframework.beans.factory.BeanCreationException
securityrat      | [WARN] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
securityrat      | org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
securityrat      | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
securityrat      | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.appsec.securityRAT.Application.main(Application.java:72) [classes!/:na]
securityrat      | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
securityrat      | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
securityrat      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
securityrat      | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
securityrat      | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [securityRAT-1.7.5.war:1.7.5]
securityrat      | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
securityrat      | Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
securityrat      | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:98) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:75) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:378) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:155) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:157) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
securityrat      | 	... 11 common frames omitted

No changes were made in the dockercompose file. All default values.

**Comment by rylyade1** [comment]
@AresSec do you still have this problem? Could you resolve this or find a work around because I don't have this problem

**Comment by AresSec** [comment]
Hi @rylyade1 ,
no, just tested it with the current version and everything works fine. Seemed to be an OS related issue then.
