### ISSUE TITLE
docker commit fails

### ISSUE THREAD

**Issue by lari22** [SecurityRAT/SecurityRAT#114]
Hi,

I would like to use the securityrat/all_in_one image for some smaller projects, but before that I need to add a few new requirements in the application (using the "requirements skeleton" menu). After this change I used "docker commit " to create a new image to have it as a template. 

But when I try to use the new image I get the following error: keytool error: java.io.IOException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. 

I tried to solve it but I did not succeed. Do you have a solution or a workaround for that?
I use Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 and Docker version 17.12.1-ce. 

Thanks.

**Comment by AresSec** [comment]
Hi @lari22 ,

sorry for the late reply. Do you use the actual dockercompose project (https://github.com/SecurityRAT/SecurityRAT-dockercompose)? I've just tested the current version and it works out of the box.

**Comment by AresSec** [comment]
Closed as this seems to be not relevant anymore.
