### ISSUE TITLE
Path within JIRA URL is not considered

### ISSUE THREAD

**Issue by ScriptGod1337** [SecurityRAT/SecurityRAT#125]
If a JIRA project URL contains a path within the URL, the REST calls are made to the incorrect URL.

e.g. using the project https://www.xxx.com/jira/browse/TEST results in REST-API calls to https://www.xxx.com/rest/... instead of calls to https://www.xxx.com/jira/rest...

**Comment by rylyade1** [comment]
Hi @ScriptGod1337 ,
we will add support for this (also reported #55 ).
