### ISSUE TITLE
No horizontal scrollbar in requirements view

### ISSUE THREAD

**Issue by ScriptGod1337** [SecurityRAT/SecurityRAT#129]
Referring to issue #126 I open this minor issue:

Having long strings in requirements view table is causing incorrect rendering of the table:
horizontal scrollbar should be visible but are not available.

Changing the zoom of the browser can be used as a workaround

![image](https://user-images.githubusercontent.com/53829529/67191703-5da15480-f3f2-11e9-8be0-f7323f89f992.png)

**Comment by rylyade1** [comment]
Hi @ScriptGod1337 ,
the horizontal scrollbar should be available at the bottom of the table. I would suggest you use the [markdown code snippet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) to wrap you code example.

**Comment by ScriptGod1337** [comment]
Hi @rylyade1,
thanks for the clarification

**Comment by AresSec** [comment]
Hi @rylyade1 ,
@ScriptGod1337 was using Jira syntax instead of Markdown. As we're not supporting Jira syntax we should at least restrict the optColumn cell width to a maximum value to avoid such kind of "ugly" cell spaces.

**Comment by rylyade1** [comment]
This is caused by the very long string without spacing (which is uncommon in normal sentences). Finding the most suitable maximum width values for different device sizes could require much effort and I am not sure it is worth it.

**Comment by AresSec** [comment]
Hey @rylyade1 ,
you're absolutely right. My proposal won't work for different devices and may cause ugly behaviour on different screens. Nevertheless having a very long string, which is not using Markdown and instead something related to the system the requirement gets exported might be something we should somehow support. 
Maybe we could use something like CSS media breakpoints:
https://getflywheel.com/layout/css-breakpoints-responsive-design-how-to/

**Comment by AresSec** [comment]
Suggestion: Markdown code block should be used instead of Jira code block tag

**Comment by ScriptGod1337** [comment]
The idea of this code snippets is to use them in Jira comments formatting - e.g. to use code snippets in different languages with correct syntax highlighting

Is it possible to support Jira comment formatting?
