### ISSUE TITLE
Show 'triggered by' value on each requirement

### ISSUE THREAD

**Issue by Anuubis** [SecurityRAT/SecurityRAT#133]
It would be awesome if you could see the 'triggered by' values on each requirement (maybe by having another info icon with hover effect).
At the moment you need to select each filter under 'tags' and look if the wanted requirement is listed.

**Comment by AresSec** [comment]
Hi @Anuubis,
do you mean with triggered by which CollectionInstances (parameters) of the artifact matches the specific requirement?

**Comment by Anuubis** [comment]
Hi @AresSec,
yes, probably.. so while filling out all the requirements you are able to see when each requirement should be reevaluated (on code change, interval, feature, data, ...).

**Comment by AresSec** [comment]
Closed as this is already part of SecurityRAT since version 1.8.x
