### ISSUE TITLE
YAMLException when trying to export requirements

### ISSUE THREAD

**Issue by simon-wessel** [SecurityRAT/SecurityRAT#136]
Hi, I'm currently on version v1.7.10 and I'm having issues exporting my requirements.

I get the following JS exception when pressing the Export button (on both file and JIRA exports):
{…}
> mark: undefined
> ​
> message: "unacceptable kind of an object to dump [object Undefined]"
> ​
> name: "YAMLException"
> ​
> reason: "unacceptable kind of an object to dump [object Undefined]"
> ​
> stack: "YAMLException@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:921:19
> writeNode@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:833:13
> writeBlockMapping@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:712:10
> writeNode@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:805:26
> writeBlockSequence@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:606:18
> writeNode@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:817:27
> writeBlockMapping@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:712:10
> writeNode@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:805:26
> writeBlockSequence@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:606:18
> writeNode@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:817:27
> writeBlockMapping@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:712:10
> writeNode@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:805:26
> writeBlockSequence@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:606:18
> writeNode@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:817:27
> writeBlockMapping@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:712:10
> writeNode@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:805:26
> dump@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:894:16
> safeDump@https://mydomain.example/bower_components/js-yaml/dist/js-yaml.js:900:10
> l.confirm@https://mydomain.example/scripts/1247acad.app.js:8631:28
> fn@https://mydomain.example/scripts/838016ef.vendor.js line 1 > Function:4:141
> t@https://mydomain.example/scripts/838016ef.vendor.js:1:249570
> $eval@https://mydomain.example/scripts/838016ef.vendor.js:1:200894
> $apply@https://mydomain.example/scripts/838016ef.vendor.js:1:201137
> compile/</<@https://mydomain.example/scripts/838016ef.vendor.js:1:249653
> dispatch@https://mydomain.example/scripts/838016ef.vendor.js:1:53264
> add/g.handle@https://mydomain.example/scripts/838016ef.vendor.js:1:51276
> "
> ​
> <prototype>: Object { constructor: YAMLException(), toString: toString(), stack: "" }
> 838016ef.vendor.js:1:177625

![grafik](https://user-images.githubusercontent.com/9195792/70548337-a82d8a80-1b72-11ea-898e-0d73aeedd80f.png)

**Comment by AresSec** [comment]
Hi @simon-wessel,
can you maybe give out more details about the configuration? I'm using also 1.7.10 and I can't reproduce the bug. Have you tried it with a basic requirement set to narrow it down to a specific use case where this happens?

**Comment by simon-wessel** [comment]
Hi @AresSec, I tried exporting one test requirement and it still threw the YAMLException. I can export empty requirement sets though.

The only non-default settings in the configuration files are for database access and mails.

**Comment by AresSec** [comment]
Hi @simon-wessel,
is your requirement set (the database) internal or would it be possible to share it with me directly so I can make a test with your requirement set in my environment to debug it?

**Comment by simon-wessel** [comment]
Thank you for the offer, but I think I found the error. The issue seems to be caused by status columns with is_enum=true. Maybe the JS YML Parser can't handle enums?

**Comment by AresSec** [comment]
Hi @simon-wessel,
is the status column actually an enumeration column? Are there values for enumeration defined? Because enumeration columns are a standard feature in SecurityRAT and do work (I've a lot of them in my instances running 1.7.10).

**Comment by simon-wessel** [comment]
Hi @AresSec,
missing status column values seemed to be the issue, but from what I've been told SecurityRAT didn't complain until upgrading to 1.7.10 (can't confirm this for sure though).
Some kind of warning about missing values might help new users, otherwise this issue can be closed.

Thank you :+1:
