### ISSUE TITLE
Old exports can't be imported after version upgrade

### ISSUE THREAD

**Issue by simon-wessel** [SecurityRAT/SecurityRAT#137]
Hi there,
we have some exports from last year which can't be imported anymore.

The import fails with the following error message:
![2020-03-05 10_14_15-SecurityRAT](https://user-images.githubusercontent.com/9195792/75966173-35f6e880-5eca-11ea-8194-481c0aec3c61.png)
> Yaml file could not be read please contact the developers.

I can provide an example file e.g. by mail for testing purposes if required. The file was created before v1.7.10 and is probably from version v1.7.9.

Kind regards

**Comment by AresSec** [comment]
Hi @simon-wessel ,
sorry for the late reply. Could you provide me an example file where I can debug the error?

**Comment by rylyade1** [comment]
Hi @simon-wessel 
I made some changes in version 1.7.11 to resolve this issue. Could you please check this and let us know?

**Comment by simon-wessel** [comment]
Hi @rylyade1, thanks a lot for having a look at this. The import itself is now successful.

There is one more error after importing. The request to `/frontend-api/categoriesWithRequirements/filte` throws a 500 HTTP error. I am assuming that one collection has been deleted since the creation of the export file. It works if I remove one of the IDs from the `collections` GET parameter.

**Comment by AresSec** [comment]
Fixed with version 1.7.11
