### ISSUE TITLE
Underscore Not allowed in Artifact Name

### ISSUE THREAD

**Issue by daniel-e** [SecurityRAT/SecurityRAT#139]
When creating a new artifact I am not able to use an underscore in the name even though it is on the whitelist of allowed characters. See screenshot.

![ratbug](https://user-images.githubusercontent.com/5294331/79456581-0a9a0a00-7fef-11ea-916c-bd1ef047e71a.png)

**Comment by AresSec** [comment]
Hi @daniel-e,
thank you for the report of this bug. We'll have a look into it and will fix it.

**Comment by AresSec** [comment]
Fixed with https://github.com/SecurityRAT/SecurityRAT/commit/f9ccd4efd410f527deaa8e2d46011e1792a2912f

**Comment by rylyade1** [comment]
Fix is part of the new Release 1.7.11
