### ISSUE TITLE
not uploading in JIRA

### ISSUE THREAD

**Issue by ipk1** [SecurityRAT/SecurityRAT#144]
Hi,

so i have configured a reverse proxy with following settings in sites-enabled/000-default.conf
ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
        ProxyPreserveHost On
        ProxyPass / http://172.16.10.55:8082/
        ProxyPassReverse / http://172.16.10.55:8082/
        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel debug
        Header always set Access-Control-Allow-Origin "*"
        Header always set Access-Control-Allow-Methods "GET,HEAD,OPTIONS,POST,DELETE"
        Header always set Access-Control-Allow-Headers "Content-Type, X-Atlassian-Token"
        Header always set Access-Control-Allow-Credentials "true"
        Header always set Access-Control-Max-Age "1000"

and in sites-available/000-default.conf
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
##reverse proxy config  
      ProxyPreserveHost On

        ProxyPass / http://172.16.10.55:8082/
        ProxyPassReverse / http://172.16.10.55:8082/

# ALLOW CORS everywhere
    Header always set Access-Control-Allow-Origin *
    Header always set Access-Control-Max-Age "1000"
    Header always set Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"

my reverse proxy ip is 172.16.10.28
JIRA version Jira v8.5.1

these setting were working with 1.7.10, now it doesnt save in jira, i have tried giving the JIRA ip in Header always set Access-Control-Allow-Origin but to no success.

the url i give in SR is 172.16.10.28/projects/AR, and also is there a way where the requirements can as users stories in 
jJIRA where it will help me map defects to the stories?

thanks
ipk1

**Comment by rylyade1** [comment]
Hi @ipk1 

your list of allowed headers is missing the `X-Atlassian-Token` header. Also, you need to configure `Access-Control-Allow-Credentials: true` to ensure that the browser sends the session cookie in the request. This is also documented [here](https://securityrat.github.io/int_jira.html).

Cheers

**Comment by ipk1** [comment]
it does now, my bad , was autofilling the wrong ip address!!closing this now, thanks for your help mate
