### ISSUE TITLE
Path within JIRA URL is not considered

### ISSUE THREAD

**Issue by ScriptGod1337** [SecurityRAT/SecurityRAT#149]
The effect described in #125 is still present in v1.7.11: the request still needs to modified manually during request to Jira API
Is this an issue or is this feature rejected?

**Comment by ScriptGod1337** [comment]
thanks. The change in branch 1.8 work partially:

During saving the artifact and after the "Export" button press, the URL is changed and the path part is removed - e.g. https://localhost/jira/browse/TEST is replaced with https://localhost/browse/TEST. Due this,
- the first request is successful and issue type, JIRA fields etc. can be selected, but
- the exporting fails - as the URL is incorrect

![jira_url_1 8](https://user-images.githubusercontent.com/53829529/108225379-2ead0700-713c-11eb-9fe4-e47ed74fb1d0.png)

Changing it back to original one (e.g. https://localhost/jira/browse/TEST) does result in the same effect and the same URL modifications applied again

**Comment by rylyade1** [comment]
Hi @ScriptGod1337 

you are right. I have updated it again. Could you please test it again?

**Comment by ScriptGod1337** [comment]
Hi @rylyade1,

thanks. I tested it.

Some request are now working and some not
![jira_url_1 8_2](https://user-images.githubusercontent.com/53829529/109132155-cc639000-7753-11eb-8445-c8de9f6c6705.png)
