### ISSUE TITLE
Demo-Credentials on https://securityrat.org

### ISSUE THREAD

**Issue by 8L4ckc0FF33** [SecurityRAT/SecurityRAT#153]
I tried to use the demo on https://securityrat.org but tying to authenticate with the demo credentials demo/SecurityRAT******! the authentication fails. Are those no longer valid? Did they change?

**Comment by AresSec** [comment]
Hi @8L4ckc0FF33 ,

thank you for the information. We made a database changed and unfortunately the demo user was not synched. I've fixed it and now authentication with the credentials of the demo user works.
