### ISSUE TITLE
SecRat link in Jira tickets doesn't contain URL path

### ISSUE THREAD

**Issue by ScriptGod1337** [SecurityRAT/SecurityRAT#165]
The linked URL to SecRat in the created Jira tickets does not contain the path component of the SecRat URL.

My SecRat is hosted behind a reverse proxy with it's own path - e.g. https://reverseproxy/secrat/ linked to http://secratinstance/. In the created Jira tickets there are links like https://reverseproxy/?ticket=.... - but this should be https://reverseproxy/secrat/?ticket=...

The link in the created Jira tickets should be defined by window.location.href instead of window.location.hostname

**Comment by AresSec** [comment]
Hi @ScriptGod1337,
I've fixed the issue in the master branch. Can you have a test with your setup and confirm that this works now?

**Comment by rylyade1** [comment]
This issue is fixed in v1.8.5.

**Comment by ScriptGod1337** [comment]
isuse is fixed. thanks
