### ISSUE TITLE
SecRat link logo doesn't contain URL path

### ISSUE THREAD

**Issue by ScriptGod1337** [SecurityRAT/SecurityRAT#166]
The linked URL to SecRat in the top logo does not does not contain the path component of the SecRat URL.

My SecRat is hosted behind a reverse proxy with it's own path - e.g. https://reverseproxy/secrat/ linked to http://secratinstance/. The link in the SecRat logo refers to https://reverseproxy/ but it should refer to https://reverseproxy/secrat/

The link should be defined by window.location.href instead of window.location.hostname

**Comment by AresSec** [comment]
Hi @ScriptGod1337,
I've fixed the issue in the master branch. Can you have a test with your setup and confirm that this works now?

**Comment by rylyade1** [comment]
This issue is fixed in v1.8.5.

**Comment by ScriptGod1337** [comment]
thanks the for change. But the navbar-brand contains "/" as URl - so path is ignored

![image](https://user-images.githubusercontent.com/53829529/165119250-2942a0ef-0ec6-4373-8048-8f1580858de0.png)
