### ISSUE TITLE
Bug in Import Assistant for key based filtering

### ISSUE THREAD

**Issue by markaltmann** [SecurityRAT/SecurityRAT#167]
**Story**: As a Security Consultant, I want to use the Import Assistant to load control catalogues like the ASVS into my SecRAT instance.
I have used the following file for reference: [OWASP Application Security Verification Standard 4.0.2-en.xlsx](https://github.com/SecurityRAT/SecurityRAT/files/7203205/OWASP.Application.Security.Verification.Standard.4.0.2-en.xlsx)

I did the following mapping/setting:

- Collection Category fixed to value "ASVS" (key to name)
- Project Type name to value ASVS and Description (key to name)
- A/B -> Collection Instance Name and Description entry (key to name)
- C/D -> Requirement Category Name and Description entry (key to name)
- E/F -> Requirement Skeleton Name and Description entry (no key needed)

When the calculation happens, though, the key is not used to identify the corresponding objects, but only the row. So objects are blindly generated and linked on a per-row basis.

Example: Collection Category:
![image](https://user-images.githubusercontent.com/6690509/134175569-68d53c87-bf65-4144-bb3f-003ee2721c57.png)

Example Requirement Category:
![image](https://user-images.githubusercontent.com/6690509/134175615-22f07916-720f-4fe2-968a-13f767723a45.png)

Example Requirement Skeleton:
![image](https://user-images.githubusercontent.com/6690509/134175657-3e5c53a6-6db4-4b14-b612-6dff859b8dd9.png)

As you can see in the last image, the mapped Category is not the correct one, fitting to the Requirement Skeleton. Or in the first one, there should only be one Collection Category, instead of the full 285 ones.

This should be fixed.

**Comment by AresSec** [comment]
Hey @markaltmann,
the Import feature was written by a student project and is currently not maintained in version 1.x. As we are still developing version 2.0 we will not further develop 1.8 nor fix this bug as is not part of the core functionality of SecurityRAT which we are still updating if there are any bugs.
Sorry
