### ISSUE TITLE
Demo Site Seems Broken

### ISSUE THREAD

**Issue by cbutler-affirm** [SecurityRAT/SecurityRAT#181]
Repro steps:
Logged in as demo user

1- Create a new artifact
2- Name artifact "Test 123"
3- Select V2 Authentication
4- Select L1
5- Click Generate

Result includes buttons that contain code (i.e. "{{requirements.length}}") and an empty list of requirements.

**Comment by AresSec** [comment]
Hi @cbutler-affirm,
thanks for the hint. There was an issue after a database update. This is fixed now and demo instance is running fine again.
