### ISSUE TITLE
Angular Module Load Error: Error: [$injector:nomod] Module 'angular-confirm' is not available!

### ISSUE THREAD

**Issue by s1l3nt-cr0w** [SecurityRAT/SecurityRAT#2]
the app is accessible but now it does not find one module - according to chrome inspector it loads a lot of js and then on console we see this error:

```
Failed to instantiate module angular-confirm due to:
Error: [$injector:nomod] Module 'angular-confirm' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

any hints?

**Comment by dkefer** [comment]
We will look into that. 

Which version of npm and nodejs are you using?
```
node -v
npm -version
```

As a workaround: in directory `src/main/webapp/bower_components/angular-confirm-modal` you'll find a file `angular-confirm.js`. Try to copy this to `angular-confirm.min.js` in the same directory.

**Comment by s1l3nt-cr0w** [comment]
Hi Daniel,

$ node -v
v4.2.6
$ npm -version
3.10.3

okay, workaround übernommen.
Meldung von Grunt:
Warning: Error: angular-confirm is not installed. Try running `bower install`. Use --force to continue.

Weiter kam ich nicht mehr, weil der Server jetzt nicht mehr reagiert.

Grüße
Cr0w

**Comment by dkefer** [comment]
Hi Cr0w,

how exactly are you using grunt? That's actually where I suspect the problem. What happened when you just copied the file and hit refresh without doing anything else?

Cheers,
Daniel

**Comment by s1l3nt-cr0w** [comment]
Good Morning Daniel,

I'm starting grunt with grunt serve. This is using following task:
`  grunt.registerTask('serve', [
        'clean:server',
        'wiredep',
        'ngconstant:dev',
        'browserSync',
        'watch'
    ]);
`
![grunt_start](https://cloud.githubusercontent.com/assets/19819836/16646544/eeb07bac-442a-11e6-94a3-7d0d927d1020.png)

The next step we starting securityrat with $ sudo mvn spring-boot:run
`OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000cdc80000, 31457280, 0) failed; error='Cannot allo                                                                                                                        cate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 31457280 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/smarthouse/SecurityRAT-master/hs_err_pid4611.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
`
Here the log:
[hs_err_pid4611.txt](https://github.com/SecurityRAT/SecurityRAT/files/351692/hs_err_pid4611.txt)

Grunt is running "watch" and is waiting.

Cheers,
Cr0w

**Comment by dalini** [comment]
We have the tool running for evaluation in an azure vm -> so you can send me/us a ssh-pub-key and also look yourself - if this might help ;). It has 3.5GB ram and 2 CPU - but of course I could also scale it up a little - look sufficient in the beginning...

Maybe it is not enough?

**Comment by AresSec** [comment]
I dropped you an email with a pubkey at the email address:
github.develop@dalini.de

2016-07-07 12:07 GMT+02:00 Ives Laaf <notifications@github.com>:

**Comment by dkefer** [comment]
I've never seen this, I usually run the image in a VM with 4GB and never ran into problems. As far as I understand this, the JVM tries to allocate just 32MB 

From your logfile:
/proc/meminfo:
MemTotal:        3521928 kB
MemFree:          111900 kB
MemAvailable:       6312 kB
...
SwapTotal:             0 kB
SwapFree:              0 kB

Maybe I would try to add a swapfile first before increasing RAM?

**Comment by s1l3nt-cr0w** [comment]
Thanks for your help.

As we found out, the problems were related to the limited amount of RAM. 
With 8GB it now runs perfectly.

Can be closed, thank you.
