### ISSUE TITLE
broken link to OWASP page

### ISSUE THREAD

**Issue by jgadsden** [SecurityRAT/SecurityRAT#203]
The link to https://owasp.org/www-project-securityrat/ gives a 404
This link is provided on the github page, and is also referenced from the [OWASP projects page](https://owasp.org/projects/)

**Comment by AresSec** [comment]
Hey @jgadsden,
yes we are aware of the topic and are already in clarification with OWASP about that.
Thanks for the Ticket. I'll close it when the links are working again

**Comment by jgadsden** [comment]
thanks @AresSec 
What is the intention for this link? I guess you still want the page on the OWASP projects site?

**Comment by jgadsden** [comment]
Hope this is OK with you @AresSec 
I have asked @ hblankenship and @alyssa-hardin if they could un-archive the project
I would like to link to https://owasp.org/www-project-securityrat/ from the OWASP Developer Guide

**Comment by AresSec** [comment]
Hey @jgadsden,
sure we still want the page as we are still an active OWASP project (see github commits and release in this org repo). I was a little but curious that they archieved it without any prior notice to us.
Thanks for asking @hblankenship and @alyssa-hardin for that issue.

**Comment by hblankenship** [comment]
Hey, @AresSec, I apologize if this was done in error with an active project. We sent out notifications on April 12, 2023 and we have it recorded that one (or more) of the project leaders contacted agreed to the archival; something crossed wires somewhere. I have un-archived the www-project-securityrat repository and would request that you update the page with any new news/releases, etc.

The project will show back up on OWASP lists within 24 hours.

**Comment by jgadsden** [comment]
Thanks @hblankenship , I can see the pages back again, much appreciated
Closing this now @AresSec as all good now

**Comment by AresSec** [comment]
Hey @jgadsden, of course that would be nice :)! I also added a watchdog on the Application itself on the Server.
