### ISSUE TITLE
Can not access demo site

### ISSUE THREAD

**Issue by jgadsden** [SecurityRAT/SecurityRAT#204]
I can not access [SecurityRAT](https://securityrat.org/), I get a ERR_HTTP2_PROTOCOL_ERROR

**Comment by AresSec** [comment]
Hi @jgadsden,
thanks for the hint. It is back online again and fixed.

Will close the ticket here now.

**Comment by jgadsden** [comment]
do you want to apply a housekeeper that checks the links, say daily? I can create a workflow for this if you think it is a good idea @AresSec

**Comment by AresSec** [comment]
Hey @jgadsden, of course that would be nice :)! I also added a watchdog on the Application itself on the Server.

**Comment by jgadsden** [comment]
Hello @AresSec , created pull request #205 and also an issue #206 for this
Also I did the same for the www-project pages, just because it all helps:

https://github.com/OWASP/www-project-securityrat/pull/7
https://github.com/OWASP/www-project-securityrat/issues/6
