### ISSUE TITLE
run a daily workflow action to check all links

### ISSUE THREAD

**Issue by jgadsden** [SecurityRAT/SecurityRAT#206]
It would be good to automate checking the links for the SecurityRAT project, in particular :
* https://securityrat.org/
* https://securityrat.github.io/
* https://owasp.org/www-project-securityrat/

**Comment by AresSec** [comment]
Hey @jgadsden,
I approved the PR and fixed a little issue within the yaml file and now the lychee link check works like a charme. Thanks for the help.

**Comment by jgadsden** [comment]
Thanks @AresSec for catching the error in the .yaml file
