### ISSUE TITLE
'Create JIRA Tickets' not compatible with Jira >= 9.0

### ISSUE THREAD

**Issue by hrobertson** [SecurityRAT/SecurityRAT#207]
The 'Create JIRA Tickets' feature does not work with Jira >= 9.0.

The function `getMandatoryFields` here https://github.com/SecurityRAT/SecurityRAT/blob/master/securityrat-frontend/src/main/webapp/scripts/app/editor/export/export.controller.js#L360 is calling `/issue/createmeta?projectKeys={projectIdOrKey}&issuetypeNames={issuetypeName}` but this endpoint no longer exists as of Jira 9.0.

It should be updated to `/issue/createmeta/{projectIdOrKey}/issuetypes/{issueTypeId}`

See https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html

Thanks

**Comment by AresSec** [comment]
Hey @hrobertson,

thanks for raising this Bug. I'm going to find out if the new URL is also backward compatible to Jira < 9.0

**Comment by hrobertson** [comment]
https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html says some endpoints have been added to Jira 8.4 to support this.

I don't know how common it is for people to be running versions < 8.4.

**Comment by AresSec** [comment]
Hey @hrobertson,
we need to find a solution which will not break functionality of running versions < 8.4 as there are still instances around which are using this old Jira version and we do not want to break it for them. I think we will come up with a fix pretty soon to support both endpoints.
