### ISSUE TITLE
FORM authentication - new user / register user is not working

### ISSUE THREAD

**Issue by dalini** [SecurityRAT/SecurityRAT#22]
At least since 1.3.0 until 1.4.2 it seems not to be possible to create a new user as admin or register itself in case of FORM authentication chosen in the production mode with the pre-build war from github used.

It might be in correlation to the ongoing notification of not being able to talk to elasticsearch - this happens even if the data-section in the yaml has been removed etc. and the documentation does not mention the requirement of elasticsearch (https://securityrat.github.io/depl_production.html)

**Comment by dkefer** [comment]
Hi, elasticsearch should be a different issue. Could you please provide the content of your application.yml (without credentials)?

**Comment by dalini** [comment]
`management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: xxx

authentication:
    type: FORM # possible values are CAS or FORM
    registration: true # restrict the registration only to the administrators by setting the value to 'false'

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: localhost # mail server
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: securityRAT@localhost # from email address


swagger:
    title: SecurityRAT
    description: SecurityRAT applications and beyond!
    version: 1.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
`

**Comment by dkefer** [comment]
How exactly does the system behave? Can you provide e.g. stacktrace? We can't reproduce this for the moment. I'm also going to update the documentation during the weekend, as now we also provide the built WAR files in GitHub releases...

**Comment by dalini** [comment]
the problem is the default setting for elasticsearch - it must be set to false - everything is fine! otherwise the system tries to talk to it and behaves strangly!

**Comment by dkefer** [comment]
I guess everything works fine so closing here.
