### ISSUE TITLE
ReverseProxy Scenario - Maillinks for Confirmation point to the system itself

### ISSUE THREAD

**Issue by dalini** [SecurityRAT/SecurityRAT#24]
I did setup an apache as reverse proxy and everything is fine except:
- the confirmation mail - in the self registration scenario - points to the localhost:port instead of the reverse proxy domain and port
- I didn't find the setting where to tell the system this so the link in the mail is adopted accordingly
- So far securityrat can't know and uses what it has - this is it's own process information (maybe I've overseen it in the config/documentation)
- https://securityrat.github.io/depl_production.html only recomends to use a revers proxy but gives no hint where to set this information

**Comment by dkefer** [comment]
Do you use mod_proxy? If so, do you have the ProxyPreserveHost directive set to On? We might mention this in the documentation...

**Comment by dkefer** [comment]
Hi @dalini , 
could you check my the proxy settings meanwhile?

Cheers,
Daniel

**Comment by dalini** [comment]
Yes I just missed the header;
