### ISSUE TITLE
Activation password is not received by several mail servers

### ISSUE THREAD

**Issue by AresSec** [SecurityRAT/SecurityRAT#27]
Version: 1.4.2

By adding a new user or the user itself registered a new user the activation password mails are not received. 
- Gmail: Mails received
- Bosch: No Mails received
- Web.de No Mails received

Maybe there is a problem with the mail server config and our mails are rejected by those mail servers.

**Comment by rylyade1** [comment]
I think i should be mail server config problem. This works perfect fine on our side.

**Comment by dkefer** [comment]
@AresSec : Have you been able to reproduce this ever since? If not, I would close this issue.

**Comment by AresSec** [comment]
No, I could not reproduce it since then. Let's close it and reopen it, if we see such an behaviour again and further analysis it.
