### ISSUE TITLE
Support SAML 2.0 as an authentication mechanism

### ISSUE THREAD

**Issue by bkimminich** [SecurityRAT/SecurityRAT#28]
It should be possible to configure SAML 2.0 as authentication mechanism in SecurityRAT to support more possibilities for authentication.

**Comment by AresSec** [comment]
Good idea. We will put that to the Backlog for Version 2.0

**Comment by r32rtb** [comment]
Is adding support for SAML still on the road-map for version 2.0?

**Comment by dkefer** [comment]
In the first place we'll go for OIDC. SAML probably only if someone contributes.

**Comment by dkefer** [comment]
These topics will be further observed in V2 and new repository structure.
