### ISSUE TITLE
Make linking between JIRA tickets optional

### ISSUE THREAD

**Issue by dkefer** [SecurityRAT/SecurityRAT#30]
Currently, the JIRA ticket is containing the YML file is linked automatically with the generated tickets for particular requirements. This behavior should be possible to override in the modal screen for ticket creation.

**Comment by rylyade1** [comment]
This is implemented when adding already existing ticket to a requirement. (v1.6.0 upwards). It also should be implemented in the creating ticket in batch mode functionality
