### ISSUE TITLE
YAML file is not valid if it contains a # (hashsign)

### ISSUE THREAD

**Issue by AresSec** [SecurityRAT/SecurityRAT#40]
If the requirement set contains a link with a hash sign, e.g. www.foobar.com/test#subchapter the method safeDump will only write until www.foobar.com/test and ends there. Afterwards an import via safeLoad is not possible as the yaml file is not valid.

An update to the current newest version 3.7.0 if js-yaml didn't fix the problem. A bug was opened in js-yaml: https://github.com/nodeca/js-yaml/issues/323

**Comment by AresSec** [comment]
Tried it with your sample code provided by js-yaml guy even with double quotes:
```javascript
console.log(jsyaml.safeDump({ a: "Test www.foobar.com/test#subchapter", b: 123 }));
a: 'Test www.foobar.com/test#subchapter'
b: 123
```

Worked like a charm. Maybe there is a problem with quotation of strings in our data.

**Comment by rylyade1** [comment]
Closing here.

**Comment by AresSec** [comment]
*ThumpsUp* @rylyade1 for that fix! Good work!

**Comment by rylyade1** [comment]
The problem only arise on export to file right?

**Comment by AresSec** [comment]
I've only checked it with the export, as this was destroying the yaml file in a not importable format. Haven't checked an import with a hashtag in an url.

**Comment by rylyade1** [comment]
The problem is not from js-yaml. The # (hashsign) was not properly encoded prior download.

**Comment by AresSec** [comment]
Have you checked import? If that's ok, I'll close the bug.

**Comment by rylyade1** [comment]
Importing works too. But leave it open since the fix is still in the dev branch.
