### ISSUE TITLE
Search functionality for entities in CRUD interface broken

### ISSUE THREAD

**Issue by AresSec** [SecurityRAT/SecurityRAT#43]
The search functionality for all entities in the CRUD interface is not working as it is not implemented and results in a 404 Not found error. 

Solution: It should be implemented via the angularJS filter functionality like in the editor/requirements done.

**Comment by rylyade1** [comment]
This functionality is implemented by jhipster with elastic search. I guess elastic search needs to be installed first.

**Comment by AresSec** [comment]
Actually not for all. For example search functionality is working for CollectionCategories but not for RequirementSkeletons or OptColumnContents. 

Nevertheless I think as we want to get rid of elasticsearch it makes sense and is also more efficient to use built-in filter ability like we use it in editor/requirements.

**Comment by AresSec** [comment]
Fixed with commit 6f4d171d9586f5d590791c866efb6569f77cc5f6.
