### ISSUE TITLE
Update available won't work if requirement category is set to active

### ISSUE THREAD

**Issue by AresSec** [SecurityRAT/SecurityRAT#44]
If one or more requirement category with requirements are set from Inactive to Active and an artifact is imported the Updates Available button pops up. By clicking no updates are shown, only all categories and not the new category.

**Comment by rylyade1** [comment]
fixed with commit [938927f](https://github.com/SecurityRAT/SecurityRAT/commit/938927fe0f25572750dbcb1a94cc434440406ddf)
