### ISSUE TITLE
[Entity Editor] Searching an entity, filter is not applied to Select All

### ISSUE THREAD

**Issue by AresSec** [SecurityRAT/SecurityRAT#45]
If a user is searching an entity in a specific entity page like RequirementSkeletons, the page is filtered to his specific search pattern. If he then clicks "Select All" and "Bulk Change" all entities are selected and not only the ones which are displayed on the page. This could lead to a huge change to the database which was actually not intended.

Solution: Select All should only select the current ones which are filtered.

**Comment by rylyade1** [comment]
fixed with commit 938927f
