### ISSUE TITLE
JIRA API at subpath

### ISSUE THREAD

**Issue by dalini** [SecurityRAT/SecurityRAT#55]
We have our jira instance running as: 

- https://domain/*jira*/ 
therefore the api is not located here: 
- https://domain/rest/api/latest/issuetype?cacheBuster=1497025329678
but instead here:
- https://domain/*jira*/rest/api/latest/issuetype?cacheBuster=1497025329678

Is there a parameter/config to change the url the system tries to talk to the api?

**Comment by dalini** [comment]
As a temporary workaround I did patch the config.js or alternatively the minified release js inside the war file - with adding the prefix:
- /rest -> /*jira*/rest and it works like a charm

For the current 1.6.0 the file is located here:
- /dist/scripts/a7159921.app.js
- search and replace the jira*-vars that reference the rest-api-calls

**Comment by dkefer** [comment]
Hi @dalini , thanks for creating the issue and for finding the solution as well! :)
 
Indeed, there is not a better one. We could make this configurable in the admin interface, but not sure it's worth the effort.  I don't find this quite a standard setup.

**Comment by dkefer** [comment]
No further steps planned for the moment -> closing here.
