### ISSUE TITLE
infiniteScroll not working for editor/requirements

### ISSUE THREAD

**Issue by AresSec** [SecurityRAT/SecurityRAT#56]
Infinite-scroll is not applied, it seems that limitTo:numberToDisplay is not working in the ng-repeat directive.

**Comment by rylyade1** [comment]
A filter by _category_ was applied before the infinite-scroll. The result of the first filter was therefore never greater that _numberToDisplay_ and rendering the _limitTo_ pretty useless.

**Comment by rylyade1** [comment]
The current infinite-scroll fix results to improper filtering. That is, some filters are not applied to the whole list of available requirements since this one has been limited by the _limitTo_. For this reason, i will revert this solution.

**Comment by AresSec** [comment]
This still not works in the requirements controller.

**Comment by rylyade1** [comment]
Yes the implemented solution was reverted. Since the _limitTo_ filter prevented the whole list of requirements from being rendered, it resulted to some filtered not being properly applied. For this reason, we decided to remove the _infiniteScroll_ functionality in this view.

**Comment by AresSec** [comment]
We should think about a solution for the requirements controller then. With more then 100 requirements (like in ASVS) the tab in the browser will be locked and firefox displays a message that a script takes too long loading. This results in a locking of the whole browser and shouldn't be the case of SecurityRAT. Maybe there is another possibility like Sliding Window to solve that issue.

**Comment by AresSec** [comment]
FIxed for the CRUD interface, not needed for the editor
