### ISSUE TITLE
First custom requirement can't be edited

### ISSUE THREAD

**Issue by masooh** [SecurityRAT/SecurityRAT#65]
Steps to reproduce:

Create requirement
1. Custom Requirements -> Add
1. Description: "First Req", Strategy: Task
1. Add requirement

Edit requirement
1. Custom Requirements -> Edit
1. Change Description: "First Req Modified"
1. Edit requirement

Nothing changed

**Comment by rylyade1** [comment]
For some reasons a change in the value of the object didn't make the change. The unmodified object was therefore remove from the array and edited one was added.
