### ISSUE TITLE
Category of custom requirement can't be edited

### ISSUE THREAD

**Issue by masooh** [SecurityRAT/SecurityRAT#66]
Steps to reproduce:
1. Custom Requirements -> Edit
1. Change Category Dropdown from "Lifecycle" to "Secure Architecture"
1. Edit requirement

Custom requirement is still in "Lifecycle" category.

This has nothing to do with #65, it also happens for custom requirements which are not the first one.

**Comment by rylyade1** [comment]
The category wasn't updated in the object after change
