### ISSUE TITLE
List of slide templates is not refreshed after creating a new slide template

### ISSUE THREAD

**Issue by phzs** [SecurityRAT/SecurityRAT#76]
Sometimes a newly created slide template will not be listed in the slide templates view after saving.

**Comment by rylyade1** [comment]
This problem could not be reproduce. Even in the heroku instance this doesn't arise.

**Comment by AresSec** [comment]
@phzs and @rylyade1 I can reproduce it even on the heroku instance (using the following browser: Firefox ESR 52.3.0) Which one have you used to reproduce it?

**Comment by rylyade1** [comment]
I used Firefox 55.0.2(64bit, Firefox 52.3.0(32bit) and chrome 61.0.3(32bit). The last two browse it did not refresh the first time but then afterwards it worked well. I will try and look into it again.

**Comment by rylyade1** [comment]
I have committed a fix. This should fix the problem. At least it did on my localhost instance. Thanks @AresSec for the input.
