### ISSUE TITLE
Update: Empty categories are not deleted when updating a training

### ISSUE THREAD

**Issue by phzs** [SecurityRAT/SecurityRAT#90]
If requirements are moved or deleted after a training has been generated so that one or more categories do not contain selected requirements they are not deleted but stay in the tree.

Underlying problem:
The results of the query which is used to get the categories with requirements that match the user's selection includes empty categories. This is also related to #81.

**Comment by phzs** [comment]
The user has the ability to remove custom slides which reside in those empty categories by using drag&drop or deleting them via the context menu. The categories themselves have no impact on the presentation (slides are only generated for custom slide nodes and generated slide nodes), as long as they do not contain any slide nodes.

**Comment by AresSec** [comment]
Marked as won't fix. Closed
