### ISSUE TITLE
Docker image will not start

### ISSUE THREAD

**Issue by azare** [SecurityRAT/SecurityRAT#93]
I downloaded the latest Docker image however if fails to start because it cannot connect to MySQL.

```
docker run -it -p 9002:9002 securityrat/all_in_one
Unable to find image 'securityrat/all_in_one:latest' locally
latest: Pulling from securityrat/all_in_one
9502adfba7f1: Pull complete
4332ffb06e4b: Pull complete
2f937cc07b5f: Pull complete
a3ed95caeb02: Pull complete
dcf4d606c56c: Pull complete
46bfedbaddf0: Pull complete
79403a769c09: Pull complete
1ce079cd04dd: Pull complete
Digest: sha256:28b30bd6f1c39edb80f488c8d9650032864fd572559ae391546778f9484cac0c
Status: Downloaded newer image for securityrat/all_in_one:latest
Certificate was added to keystore
Warning: Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

Any thoughts?

**Comment by dkefer** [comment]
Hi @azare,

thanks for providing feedback! I've just tried on my system (Linux) and everything works smoothly. What OS and Docker version are you using?

Cheers,
Daniel

**Comment by azare** [comment]
Hi @dkefer,
I'm on macOS 10.12.6 running Docker version 17.06.2-ce, build cec0b72

**Comment by AresSec** [comment]
Hi @azare and @dkefer ,

I just tried it on Ubuntu Linux version 4.10.0-35-generic and I got the same error message as @azare:

```
sudo docker run -it -p 9002:9002 securityrat/all_in_one
Certificate was added to keystore
Warning: Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by AresSec** [comment]
Maybe there is a problem with the following line:

MYSQL_ROOT_PASSWORD="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32})"

`# /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32}
sh: 3: /dev/urandom: Permission denied`

**Comment by AresSec** [comment]
Ok, I think I figured it out. There is a problem within in the docker-entrypoint.sh

First of all starting the mysql_install_db with basedir results in an InnoDB error in the mysql error.logs. Instead of:

`mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql &>/dev/null &`

The parameter basedir should be ommited:

`mysql_install_db --user=mysql --datadir=/var/lib/mysql &>/dev/null &`

Second, there is a problem with the debian mysql user "user     = debian-sys-maint". The user does not have the privileges to connect to the mysql, but it should be able to connect to it. After mysql_install_db add the following command:

`dpkg-reconfigure mysql-server`

With those changes the docker container started without any errors and SecurityRAT started fine.

**Comment by azare** [comment]
Hi @dkefer,

I made those changes and I know longer see the error I don't think its still starting up correctly. I never see the message that MySQL is starting or that SecurityRAT is starting.

Since I was still having issues on macOS I tried starting it on Ubuntu 14.04. I was able to successfully able to get the image running on that.

I'm happy to continue helping to troubleshoot this on macOS if you have any thoughts what may be wrong.

Here is the docker-entrypoint.sh file I modified:
cat docker-entrypoint.sh
#!/bin/bash

set -e

MYSQL_ROOT_PASSWORD="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32})"

KEYSTORE_SECURITYRAT_PASSWORD="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32})"

DATABASE_NAME="securityrat"

COMPRESSFILE="securityRAT*.tar.gz"

target="/home/securityrat/SecurityRATProd"

cd $target

tar -xzf $COMPRESSFILE

keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650 -storepass "$(echo $KEYSTORE_SECURITYRAT_PASSWORD)" -dname "CN=localhost, OU=unknown, O=unknown, L=unknown, S=unknown, C=unknown" -keypass "$(echo $KEYSTORE_SECURITYRAT_PASSWORD)"
certLocation="$(find / -name "cacerts" | grep java-8)"
keytool -import -trustcacerts -noprompt -file /etc/ssl/certs/apache.crt -keystore "$(echo $certLocation)" -storepass "changeit"

#Changes the keystore password and mysql root password accordingly in the security rat configuration file
sed -i "s/key-store-password:.*\$/key-store-password: $(echo $KEYSTORE_SECURITYRAT_PASSWORD)/" $target/config/application-dev.yml
sed -i "s/^\([[:blank:]]*\)password:.*/\1password: $(echo $MYSQL_ROOT_PASSWORD)/g" $target/config/application-dev.yml
sed -i "s/^\([[:blank:]]*\)type:.*/\1type: FORM/g" $target/config/application.yml

**mysql_install_db --user=mysql --datadir=/var/lib/mysql &>/dev/null &**

**dpkg-reconfigure mysql-server**

# set the root password
/etc/init.d/mysql stop &>/dev/null &&
echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$MYSQL_ROOT_PASSWORD');" >> /home/mysql-init
chown mysql:mysql /home/mysql-init
mysqld_safe --init-file=/home/mysql-init &> /dev/null &
sleep 20
rm /home/mysql-init
/etc/init.d/mysql start &

#create the securityrat database
mysql -u "root" "-p$MYSQL_ROOT_PASSWORD" << EOF
	create database $DATABASE_NAME;
EOF

/etc/init.d/apache2 restart &>/dev/null &&

echo
echo
echo -n "STARTING SECURITYRAT ."

while true;
do
	mysql -u "root" "-p$MYSQL_ROOT_PASSWORD" -e "select 1 from CONFIGCONSTANT" "$DATABASE_NAME" 2> /dev/null | grep 1 > /dev/null && {
		mysql -u "root" "-p$MYSQL_ROOT_PASSWORD" "$DATABASE_NAME" < "/home/securityrat/Security-Requirements/requirements.sql" &> /dev/null
		sleep 60
		echo
		echo
		echo "SECURITYRAT IS NOW RUNNING. GO TO https://localhost:9002"
		break
	}
	echo -n '.'
	sleep 1
done &

cd $target
su -m -c "java -jar $(ls | egrep .*\.war$) --spring.profiles.active=dev --1> app.log" securityrat

**Comment by dkefer** [comment]
Hi @azare and @AresSec ,

thanks for your debugging efforts! Unfortunately I don't have a Mac device to find out what's not working and also don't have a spontaneous idea what might not be working. 

We're also working replacing this image with a cleaner Docker Compose way (the effort is almost done, but just lying around for the moment). I'd suggest that we prioritize that effort higher and discontinue this image unless you're more eager to debug.

Cheers,
Daniel

**Comment by azare** [comment]
Hi @dkefer,

Since you're working on a new image I don't think it makes sense to spend time on this one. Let me know if you'd like me to test out the new image on macOS for you.

Thanks,
Erik

**Comment by dkefer** [comment]
Hi @azare ,

with 1.7.3, we introduced Docker Compose support, please see https://github.com/SecurityRAT/SecurityRAT-dockercompose. 

Does that work for you?

Best, 
Daniel

**Comment by azare** [comment]
Hi @dkefer,

Thanks and sorry I forgot to get back to your earlier. This is working for me now. 

Thanks!
Erik

**Comment by dkefer** [comment]
Perfect, closing here!
